schema_version = 1

[target.riscv64.addition]
toolchain = "riscv64-linux"
pipeline = "linked-executable"
product = "executable"

sources = [
	{ path = "src/addition.c", language = "c"},
]
output = "riscv64/addition"
formats = ["elf", "bin", "ihex", "srec"]

[target.riscv64.addition.tool_args]
compile_c = ["-O0", "-g",]
link = ["-Wl,--build-id=sha1"]

[target.riscv64.hello-world]
toolchain = "riscv64-linux"
pipeline = "linked-executable"
product = "executable"

sources = [
	{ path = "src/hello-world.c", language = "c"},
]
output = "riscv64/hello-world"
formats = ["elf", "bin", "ihex", "srec"]

[target.riscv64.hello-world.tool_args]
compile_c = ["-O0", "-g",]
link = ["-Wl,--build-id=sha1"]
