# defining a new binary target:
# [target.ARCH.BINARY-NAME]
# toolchain = "toolchain-from.toml"
# 
# source = ["invocation/path.c"]
# output = "BINARY-NAME.out"
# format = "bin"
# 
# cflags = [ ... ]


[target.riscv64.linux-elf-addition]
toolchain = "riscv64-linux"

# define multiple sources to be compiled 
sources = ["src/basic.c"]
output = "riscv64-le-addition.elf"
format = "elf"

cflags = [
 "-O0",
 "-g",
]

[target.riscv64.linux-elf-hello-world]
toolchain = "riscv64-linux"

sources = ["src/hello-world.c"]
output = "riscv64-le-hello-world"
format = "elf"

cflags = [
 "-O0",
 "-g",
]
