# use this file to define the tool chains that 
# docker should use for each target arch.
#
# hopefully will allow for easy addition of arches
schema_version = 1

[environments.debian-bookworm-riscv64]
kind = "container"
provisioner = "apt"

packages = [
	 "gcc-riscv64-linux-gnu",
	 "binutils-riscv64-linux-gnu",
	 "libc6-dev-riscv64-cross",
]

[toolchains.riscv64-linux]
environment = "debian-bookworm-riscv64"
target_triple = "riscv64-linux-gnu"
convention = "gnu"

[toolchains.riscv64-linux.tools.compile_c]
command = ["riscv64-linux-gnu-gcc"]
fixed_args = [
	"-march=rv64gc",
	"-mabi=lp64d",
]

[toolchains.riscv64-linux.tools.link]
command = ["riscv64-linux-gnu-gcc"]
fixed_args = [
	"-march=rv64gc",
	"-mabi=lp64d",
]

[toolchains.riscv64-linux.tools.convert_object]
command = ["riscv64-linux-gnu-objcopy"]
fixed_args = []

[toolchains.riscv64-linux.tools.inspect_elf]
command = ["riscv64-linux-gnu-readelf"]
fixed_args = []

